FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

RUN npm install -g prisma

COPY . .

RUN npx prisma generate

EXPOSE 9009

CMD ["npm", "run", "start:prod"]
