version: '3'
services:
    thetiptop_backend_prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.thetiptop_backend_prod.rule=Host(`api.dsp5-archi-f23-15m-g4.fr`)'
            - 'traefik.http.services.thetiptop_backend_prod.loadbalancer.server.port=9009'
            - 'traefik.http.routers.thetiptop_backend_prod.tls=true'
            - 'traefik.http.routers.thetiptop_backend_prod.tls.certresolver=le'
        networks:
            - ci-cd-network

networks:
    ci-cd-network:
        driver: bridge
        external: true
