version: '3'
services:
  thetiptop_front_uat:
    build:
      context: .
      dockerfile: Dockerfile.uat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thetiptop_front_uat.rule=Host(`uat.dsp5-archi-f23-15m-g4.fr`)"
      - "traefik.http.services.thetiptop_front_uat.loadbalancer.server.port=80"
      - "traefik.http.routers.thetiptop_front_uat.tls=true"
      - "traefik.http.routers.thetiptop_front_uat.tls.certresolver=le"
    networks:
      - ci-cd-network
      
networks:
  ci-cd-network:
    external: true
